architecture: CornerNetSqueeze
train_feed: CornerNetTrainFeed
eval_feed: CornerNetEvalFeed
test_feed: CornerNetTestFeed
use_gpu: true
max_iters: 1
log_smooth_window: 1
log_iter: 1
save_dir: debug_output
snapshot_iter: 10000
metric: COCO
pretrain_weights: NULL
weights: output/cornernet_squeeze/model_final
num_classes: 80
stack: 2

CornerNetSqueeze:
  backbone: Hourglass
  corner_head: CornerHead
  nms: MultiClassSoftNMS

MultiClassSoftNMS:
  keep_top_k: 100
  score_threshold: 0.001

Hourglass: {}

CornerHead:
  train_batch_size: 2
  ae_threshold: 0.5
  num_dets: 100
  top_k: 20 
    
LearningRate:
  base_lr: 0.00025
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 450000

OptimizerBuilder:
  optimizer:
    type: Adam
  regularizer: 
    factor: 0.0
    type: L2

CornerNetTrainFeed:
  batch_size: 2 
  dataset:
    dataset_dir: dataset/coco
    annotation: annotations/instances_val2017_debug_corner.json
    image_dir: val2017
  num_workers: 1 
  bufsize: 128
  use_process: false

CornerNetEvalFeed:
  batch_size: 1
  dataset:
    dataset_dir: dataset/coco
    annotation: annotations/instances_val2017.json
    image_dir: val2017

CornerNetTestFeed:
  batch_size: 1
  dataset:
    annotation: dataset/coco/annotations/instances_val2017.json
